# Generated by Django 3.1.7 on 2021-03-29 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naiss', models.DateTimeField(blank=True, null=True)),
                ('sexe', models.PositiveSmallIntegerField(choices=[(1, 'Feminin'), (2, 'Masculin')])),
                ('telephone', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('estvalide', models.BooleanField(default=False)),
                ('estsatisfaisant', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pjmanager.type')),
            ],
            options={
                'db_table': 'projet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserHasProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Developpeur'), (2, 'Designer')], null=True)),
                ('user_statut', models.PositiveSmallIntegerField(choices=[(1, 'responsable'), (2, 'participant'), (3, 'superviseur')], default=2)),
                ('created_at', models.CharField(blank=True, max_length=45, null=True)),
                ('projet', models.OneToOneField(db_column='Projet_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pjmanager.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_has_projet',
                'managed': True,
                'unique_together': {('projet', 'user')},
            },
        ),
    ]
