# Generated by Django 3.1.7 on 2021-03-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
