# Generated by Django 3.1.7 on 2021-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0003_auto_20210329_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
