# Generated by Django 3.1.7 on 2021-03-31 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0004_auto_20210331_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhasprojet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
