# Generated by Django 3.1.7 on 2021-03-31 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0005_auto_20210331_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhasprojet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
