# Generated by Django 3.1.7 on 2021-04-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0009_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
