# Generated by Django 3.1.7 on 2021-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0011_historicalprojet_historicaltype_historicaluser_historicaluserhasprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.IntegerField()),
                ('history_date', models.DateTimeField()),
                ('history_user_id', models.IntegerField()),
                ('history_type', models.CharField(max_length=1)),
                ('object', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
    ]
