# Generated by Django 3.1.7 on 2021-04-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0012_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserhasprojet',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserhasprojet',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='historicaluserhasprojet',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalProjet',
        ),
        migrations.DeleteModel(
            name='HistoricalType',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
        migrations.DeleteModel(
            name='HistoricalUserHasProjet',
        ),
    ]
