# Generated by Django 3.1.7 on 2021-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjmanager', '0016_auto_20210408_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltype',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
